### ISSUE TITLE
can I run: ./non-lin-search -q -o "9F0EFF2A040C7539"？

### ISSUE THREAD

**Issue by hongmerly** [vdasu/lighter-r#4]
hello， can I run: ./non-lin-search -q -o "9F0EFF2A040C7539"？There are some duplicate outputs of this box, which are different from others.

**Comment by anubhab001** [comment]
Hello @hongmerly, you will not get any output since the SBox is non-bijective (which you noted as "some duplicate outputs"). Ligther-R only works with bijective SBoxes.

(By the way, you need to specify a [library](https://github.com/vdasu/lighter-r/issues/3#issuecomment-1523086900) for the tool to work).

**Comment by hongmerly** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by anubhab001** [comment]
好的!
